version: '3'
services:
    main:
        container_name: ordina-pubquiz
        build:
            context: .
            dockerfile: Dockerfile
        image: ordina-pubquiz_main

    postgres:
        container_name: postgres
        image: postgres:9.6.2-alpine
        restart: always
        environment:
          - POSTGRES_DB=ordina-pubquiz
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
        ports:
          - 5432:5432
     
        volumes:
           - db_volume:/var/lib/postgreql

    sonarqube:
      image: sonarqube
      expose:
        - 9000
      ports:
        - 9000:9000
      networks:
        - sonarnet
     # environment:
     #   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
     #   - SONARQUBE_JDBC_USERNAME=sonar
     #   - SONARQUBE_JDBC_PASSWORD=sonar
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions

    jenkins:
      image: jenkins/jenkins
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        - jenkins_data:/jenkins_data
    backend:
        container_name: ordina-pubquiz_backend
        build:
           context: .
           dockerfile: Dockerfile-backend
        image: ordina-pubquiz_backend
        volumes:
          - "./:/usr/src/app"
          - /usr/src/app/view

    webapp:
        build:
          context: .
          dockerfile: Dockerfile-webapp
        volumes:
          - "./:/usr/src/app/"
        ports:
          - 5000:5000
        links:
          - postgres

networks:
  sonarnet:
    driver: bridge

volumes:
    db_volume:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    jenkins_data:
      driver: local
