FROM ordina-pubquiz_main
ENV FLASK_APP "home.py"
ENV FLASK_ENV "development"
ENV FLASK_DEBUG True
ENV POSTGRES_DB ordina-pubquiz
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_HOST postgres
ENV POSTGRES_PORT 5432

EXPOSE 5000

CMD flask run --host=0.0.0.0
