version: '3'
services:
    postgres:
        image: postgres:9.6.2-alpine
        restart: always
        ports:
          - 5432:5432
        volumes:
          -  db_volume:/var/lib/postgreql
        environment:
          - POSTGRES_DB=ordina-pubquiz
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
          
    backend:
        image: pubquiz-backend
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - "./:/usr/src/app"
        ports:
          - 5000:5000
       
          
    
          
volumes:
    db_volume: