version: '3'
services:
    main:
        container_name: ordina-pubquiz
        build:
            context: .
            dockerfile: Dockerfile
        image: ordina-pubquiz_main        
    postgres:
        container_name: postgres
        image: postgres:9.6.2-alpine
        restart: always
        environment:
          - POSTGRES_DB=ordina-pubquiz
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
        ports:
          - 5432:5432
     
        volumes:
           - db_volume:/var/lib/postgreql
        
      
    backend:
        container_name: ordina-pubquiz_backend
        build:
           context: .
           dockerfile: Dockerfile-backend
        image: ordina-pubquiz_backend
        volumes:
          - "./:/usr/src/app"
          - /usr/src/app/view
          
    webapp:
        build:
          context: .
          dockerfile: Dockerfile-webapp
        volumes:
          - "./:/usr/src/app/"
        ports:
          - 5000:5000
        links:
          - postgres
       
       
volumes:
    db_volume: