version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6.2-alpine
        restart: always
        environment:
          - POSTGRES_DB=ordina-pubquiz
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
        ports:
          - 5432:5432
     
        volumes:
           - db_volume:/var/lib/postgreql
        
      
    backend:
        build:
           context: .
           dockerfile: Dockerfile-backend
        volumes:
          - "./:/usr/src/app"
          - /usr/src/app/view      
          
    webapp:
        build:
          context: .
          dockerfile: Dockerfile-webapp
        volumes:
          - "./view:/usr/src/app/view"
          - "./migrations:/usr/src/app/migrations"
        ports:
          - 5000:5000
        links:
          - postgres
       
       
volumes:
    db_volume: