version: '3'
services:
    main:
        container_name: ordina-pubquiz
        build:
            context: .
            dockerfile: Dockerfile
        image: ordina-pubquiz_main
        volumes:
          - "./:/usr/src/app/"
        ports:
          - 5000:5000

