"""add table Line

Revision ID: 1c07a3d769ad
Revises: 90c76c8fd150
Create Date: 2019-12-10 13:41:23.448439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c07a3d769ad'
down_revision = '90c76c8fd150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subanswergiven_id', sa.Integer(), nullable=True),
    sa.Column('line_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subanswergiven_id'], ['subanswergiven.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('subanswergiven', 'answer_image')
    op.drop_column('subanswergiven', 'image_height')
    op.drop_column('subanswergiven', 'image_width')
    op.add_column('word', sa.Column('line_id', sa.Integer(), nullable=True))
    op.drop_constraint('word_subanswergiven_id_fkey', 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'line', ['line_id'], ['id'])
    op.drop_column('word', 'subanswergiven_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('subanswergiven_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.create_foreign_key('word_subanswergiven_id_fkey', 'word', 'subanswergiven', ['subanswergiven_id'], ['id'])
    op.drop_column('word', 'line_id')
    op.add_column('subanswergiven', sa.Column('image_width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subanswergiven', sa.Column('image_height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subanswergiven', sa.Column('answer_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_table('line')
    # ### end Alembic commands ###
