"""add answergiven table

Revision ID: 367e2ded7ca7
Revises: b38fef845c7a
Create Date: 2020-01-17 09:07:49.731665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367e2ded7ca7'
down_revision = 'b38fef845c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answergiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subanswergiven', sa.Column('answergiven_id', sa.Integer(), nullable=False))
    op.add_column('subanswergiven', sa.Column('read_answer', sa.String(length=255), nullable=True))
    op.drop_constraint('subanswergiven_team_id_fkey', 'subanswergiven', type_='foreignkey')
    op.drop_constraint('subanswergiven_question_id_fkey', 'subanswergiven', type_='foreignkey')
    op.create_foreign_key(None, 'subanswergiven', 'answergiven', ['answergiven_id'], ['id'])
    op.drop_column('subanswergiven', 'team_id')
    op.drop_column('subanswergiven', 'question_id')
    op.drop_column('subanswergiven', 'answer_given')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('answer_given', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subanswergiven', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subanswergiven', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subanswergiven', type_='foreignkey')
    op.create_foreign_key('subanswergiven_question_id_fkey', 'subanswergiven', 'question', ['question_id'], ['id'])
    op.create_foreign_key('subanswergiven_team_id_fkey', 'subanswergiven', 'team', ['team_id'], ['id'])
    op.drop_column('subanswergiven', 'read_answer')
    op.drop_column('subanswergiven', 'answergiven_id')
    op.drop_table('answergiven')
    # ### end Alembic commands ###
