"""add all tables

Revision ID: 584a1ae60bed
Revises: 
Create Date: 2020-02-24 08:53:32.648737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584a1ae60bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personname', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(length=255), nullable=True),
    sa.Column('question_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answersheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('answersheet_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnumber', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('word_recognised', sa.String(length=255), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('word_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answergiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answersheetquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answersheet_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answersheet_id'], ['answersheet.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subanswergiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corr_answer_id', sa.Integer(), nullable=False),
    sa.Column('read_answer', sa.String(length=255), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('probability_read_answer', sa.Float(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('answergiven_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answergiven_id'], ['answergiven.id'], ),
    sa.ForeignKeyConstraint(['corr_answer_id'], ['subanswer.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subanswer_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('isNumber', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subanswer_id'], ['subanswer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant')
    op.drop_table('subanswergiven')
    op.drop_table('subanswer')
    op.drop_table('answersheetquestion')
    op.drop_table('answergiven')
    op.drop_table('word')
    op.drop_table('question')
    op.drop_table('answersheet')
    op.drop_table('type')
    op.drop_table('team')
    op.drop_table('questionnumber')
    op.drop_table('person')
    op.drop_table('line')
    op.drop_table('category')
    # ### end Alembic commands ###
