"""add questionnumber column

Revision ID: 58f7a2362925
Revises: c6bac8a78e29
Create Date: 2019-12-13 14:58:21.483587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58f7a2362925'
down_revision = 'c6bac8a78e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password')
    op.add_column('subanswergiven', sa.Column('line_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subanswergiven', 'line', ['line_id'], ['id'])
    op.add_column('question', sa.Column('questionnumber', sa.Integer(), nullable=True))
    op.drop_column('subanswergiven', 'image_width')
    op.drop_column('subanswergiven', 'image_height')
    op.drop_column('subanswergiven', 'answer_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('answer_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('subanswergiven', sa.Column('image_height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subanswergiven', sa.Column('image_width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('question', 'questionnumber')
    op.add_column('person', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
