"""empty message

Revision ID: 62f36d903c71
Revises: bb6a9b039e53
Create Date: 2019-12-11 09:56:19.496172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f36d903c71'
down_revision = 'bb6a9b039e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('question_id', sa.Integer(), nullable=False))
    op.add_column('subanswergiven', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subanswergiven', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'subanswergiven', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subanswergiven', type_='foreignkey')
    op.drop_constraint(None, 'subanswergiven', type_='foreignkey')
    op.drop_column('subanswergiven', 'team_id')
    op.drop_column('subanswergiven', 'question_id')
    # ### end Alembic commands ###
