"""empty message

Revision ID: 69b674fce505
Revises: 8854bfb50c18
Create Date: 2019-12-11 10:35:34.218936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b674fce505'
down_revision = '8854bfb50c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('corr_answer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subanswergiven', 'subanswer', ['corr_answer_id'], ['id'])
    op.drop_column('subanswergiven', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subanswergiven', type_='foreignkey')
    op.drop_column('subanswergiven', 'corr_answer_id')
    # ### end Alembic commands ###
