"""added a question number column for question number recognition test

Revision ID: 72dac33f7cfe
Revises: 43f7a6ccbf73
Create Date: 2020-01-10 16:14:06.311155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision='72dac33f7cfe'
down_revision='43f7a6ccbf73'
branch_labels=None
depends_on=None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(length=255), nullable=True),
    sa.Column('question_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_number')
    # ### end Alembic commands ###
