"""test

Revision ID: 85fcffead2e9
Revises: 917f343d37b3
Create Date: 2020-01-30 11:48:15.645783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fcffead2e9'
down_revision = '917f343d37b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'probability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('probability', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
