"""empty message

Revision ID: 8854bfb50c18
Revises: 62f36d903c71
Create Date: 2019-12-11 10:34:11.667675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8854bfb50c18'
down_revision = '62f36d903c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.add_column('subanswergiven', sa.Column('corr_answer_id', sa.Integer(), nullable=False))
    op.drop_constraint('subanswergiven_answer_id_fkey', 'subanswergiven', type_='foreignkey')
    op.create_foreign_key(None, 'subanswergiven', 'subanswer', ['corr_answer_id'], ['id'])
    op.drop_column('subanswergiven', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subanswergiven', type_='foreignkey')
    op.create_foreign_key('subanswergiven_answer_id_fkey', 'subanswergiven', 'answer', ['answer_id'], ['id'])
    op.drop_column('subanswergiven', 'corr_answer_id')
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='answer_question_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='answer_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answer_pkey')
    )
    # ### end Alembic commands ###
