"""empty message

Revision ID: 889e8a5e520b
Revises: a7aaaf18ad75
Create Date: 2019-12-10 13:05:10.727493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '889e8a5e520b'
down_revision = 'a7aaaf18ad75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personname', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subanswergiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer_given', sa.String(length=255), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('answer_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subanswer_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('isNumber', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subanswer_id'], ['subanswer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subanswergiven_id', sa.Integer(), nullable=True),
    sa.Column('word_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subanswergiven_id'], ['subanswergiven.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_constraint('answer_user_id_fkey', 'answer', type_='foreignkey')
    op.drop_column('answer', 'confidence')
    op.drop_column('answer', 'user_id')
    op.drop_column('answer', 'answer_image')
    op.drop_column('answer', 'correct')
    op.add_column('answersheet', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('answersheet', sa.Column('image_width', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_constraint('question_user_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'question', 'category', ['category_id'], ['id'])
    op.drop_column('question', 'correct_answer')
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('correct_answer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_user_id_fkey', 'question', 'user', ['user_id'], ['id'])
    op.drop_column('question', 'person_id')
    op.drop_column('answersheet', 'image_width')
    op.drop_column('answersheet', 'image_height')
    op.add_column('answer', sa.Column('correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('confidence', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('answer_user_id_fkey', 'answer', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('word')
    op.drop_table('variant')
    op.drop_table('subanswergiven')
    op.drop_table('subanswer')
    op.drop_table('person')
    # ### end Alembic commands ###
