"""probability for word

Revision ID: 917f343d37b3
Revises: 6a0c09b9c8d2
Create Date: 2020-01-30 10:24:42.398976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917f343d37b3'
down_revision = '6a0c09b9c8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('probability', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'probability')
    # ### end Alembic commands ###
