"""add password column

Revision ID: a134f40ee7d3
Revises: 58f7a2362925
Create Date: 2019-12-16 14:05:28.156468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a134f40ee7d3'
down_revision = '58f7a2362925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password_hash')
    # ### end Alembic commands ###
