"""empty message

Revision ID: a30c3af88368
Revises: 
Create Date: 2019-12-04 12:05:07.638940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30c3af88368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer', sa.String(length=255), nullable=True))
    op.add_column('answersheet', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('answersheet', sa.Column('image_width', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('answersheet', 'image_width')
    op.drop_column('answersheet', 'image_height')
    op.drop_column('answer', 'answer')
    # ### end Alembic commands ###
