"""add table name reference

Revision ID: ac415e4b6bd4
Revises: 72dac33f7cfe
Create Date: 2020-01-10 16:17:56.549260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac415e4b6bd4'
down_revision = '72dac33f7cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(length=255), nullable=True),
    sa.Column('question_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_number',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question_image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('image_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_number_pkey')
    )
    op.drop_table('questionnumber')
    # ### end Alembic commands ###
