"""empty message

Revision ID: b44dab8640a1
Revises: a090747b91bd
Create Date: 2019-12-04 12:15:43.039861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44dab8640a1'
down_revision = 'a090747b91bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer_given', sa.String(length=255), nullable=True))
    op.add_column('answersheet', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('answersheet', sa.Column('image_width', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('answersheet', 'image_width')
    op.drop_column('answersheet', 'image_height')
    op.drop_column('answer', 'answer_given')
    # ### end Alembic commands ###
