"""empty message

Revision ID: b5554a1d3724
Revises: bfb1c4d96bf2
Create Date: 2019-12-04 12:23:46.464182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5554a1d3724'
down_revision = 'bfb1c4d96bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answer', sa.Column('answer_given', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.add_column('answersheet', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('answersheet', sa.Column('image_width', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answersheetquestion', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answersheetquestion', type_='foreignkey')
    op.drop_column('answersheet', 'image_width')
    op.drop_column('answersheet', 'image_height')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'answer_given')
    op.drop_table('question')
    # ### end Alembic commands ###
