"""add probability linereading for subanswergiven

Revision ID: b87fc4281d2c
Revises: e07188bfe7c5
Create Date: 2020-01-30 14:08:33.570957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87fc4281d2c'
down_revision = 'e07188bfe7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subanswergiven', sa.Column('probability_read_answer', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subanswergiven', 'probability_read_answer')
    # ### end Alembic commands ###
