"""empty message

Revision ID: bb6a9b039e53
Revises: 889e8a5e520b
Create Date: 2019-12-10 15:09:03.789655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6a9b039e53'
down_revision = '889e8a5e520b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_person_id_fkey', 'answer', type_='foreignkey')
    op.drop_column('answer', 'person_id')
    op.add_column('subanswergiven', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subanswergiven', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subanswergiven', type_='foreignkey')
    op.drop_column('subanswergiven', 'person_id')
    op.add_column('answer', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('answer_person_id_fkey', 'answer', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###
