"""created reference to teams in answersheet

Revision ID: c6bac8a78e29
Revises: 41e7e8f4b631
Create Date: 2019-12-12 11:31:04.118057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bac8a78e29'
down_revision = '41e7e8f4b631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answersheet', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answersheet', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answersheet', type_='foreignkey')
    op.drop_column('answersheet', 'team_id')
    # ### end Alembic commands ###
