"""empty message

Revision ID: d74c4b1d6714
Revises: ead8377efa5b
Create Date: 2019-12-06 08:22:34.100734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd74c4b1d6714'
down_revision = 'ead8377efa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subanswergiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer_given', sa.String(length=255), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('answer_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('answer', 'answer_given')
    op.drop_column('answer', 'answer_image')
    op.drop_column('answer', 'image_height')
    op.drop_column('answer', 'image_width')
    op.drop_column('answer', 'correct')
    op.drop_column('answer', 'confidence')
    op.add_column('variant', sa.Column('isNumber', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant', 'isNumber')
    op.add_column('answer', sa.Column('confidence', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('image_width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('image_height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_given', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('subanswergiven')
    # ### end Alembic commands ###
