"""change probability to float

Revision ID: e07188bfe7c5
Revises: 85fcffead2e9
Create Date: 2020-01-30 11:49:15.163675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07188bfe7c5'
down_revision = '85fcffead2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'probability')
    # ### end Alembic commands ###
