"""empty message

Revision ID: ead8377efa5b
Revises: 9ccec69a6f36
Create Date: 2019-12-06 07:55:17.884241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead8377efa5b'
down_revision = '9ccec69a6f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subanswer_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['subanswer_id'], ['subanswer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('question', 'correct_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('correct_answer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('variant')
    op.drop_table('subanswer')
    # ### end Alembic commands ###
