"""added Word table

Revision ID: ecdcdc9ac01d
Revises: d74c4b1d6714
Create Date: 2019-12-06 13:13:20.871398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdcdc9ac01d'
down_revision = 'd74c4b1d6714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subanswergiven_id', sa.Integer(), nullable=True),
    sa.Column('word_image', sa.LargeBinary(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subanswergiven_id'], ['subanswergiven.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
