"""changed the foreign key reference on the line table

Revision ID: ee93ac0767c5
Revises: 1c07a3d769ad
Create Date: 2019-12-10 13:53:33.361405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee93ac0767c5'
down_revision = '1c07a3d769ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line', sa.Column('answersheet_id', sa.Integer(), nullable=True))
    op.drop_constraint('line_subanswergiven_id_fkey', 'line', type_='foreignkey')
    op.create_foreign_key(None, 'line', 'answersheet', ['answersheet_id'], ['id'])
    op.drop_column('line', 'subanswergiven_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line', sa.Column('subanswergiven_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'line', type_='foreignkey')
    op.create_foreign_key('line_subanswergiven_id_fkey', 'line', 'subanswergiven', ['subanswergiven_id'], ['id'])
    op.drop_column('line', 'answersheet_id')
    # ### end Alembic commands ###
