"""add width and height to answersheet

Revision ID: efdf2f6f8126
Revises: aaae76ff57f5
Create Date: 2019-12-04 10:16:48.988189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdf2f6f8126'
down_revision = 'aaae76ff57f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answersheet', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('answersheet', sa.Column('image_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answersheet', 'image_width')
    op.drop_column('answersheet', 'image_height')
    # ### end Alembic commands ###
