"""teams table

Revision ID: 2133842212ce
Revises: 
Create Date: 2019-11-21 08:18:39.122001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2133842212ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('teamid', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('teamid')
    )
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('teamid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teamname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('team')
    # ### end Alembic commands ###
